server:
  compression:
    enabled: true # If response compression is enabled.
  context-path: /diamonds
  display-name: TTC Diamonds # Display name of the application.
  error.include-stacktrace: always # When to include a "stacktrace" attribute. default is never
  port: 8080 # Server HTTP port.
  tomcat:
    basedir: tomcat # Tomcat base directory. If not specified a temporary directory will be used.
    accesslog:
      directory: ../log/ # Directory in which log files are created. Can be relative to the tomcat base dir or absolute.
      enabled: true # Enable access log.
      pattern: common # Format pattern for access logs.
      prefix: access # Log file name prefix.
      suffix: .log # Log file name suffix.

  uri-encoding: UTF-8 # Character encoding to use to decode the URI.

spring:
  servlet:
    multipart:
        max-file-size: 50MB
        max-request-size: 100MB
        enabled: true

security:
    oauth2:
      resource:
        filter-order: 3
    jwt:
      client-id: diamonds-app
      client-secret: shshshimhuntingwabit
      grant-type: password
      scope-read: read
      scope-write: write
      resource-ids: diamonds-app-resource-id
    signing-key: MaYzkSjmkzPC57L
    encoding-strength: 256
    security-realm: Diamonds app realm

diamonds:
  host: localhost
  base-url: http://${diamonds.host}:${server.port}
  datasource:
    username:  root # Do not specify DB username here otherwise application-{env} value is not used
    password:  1234 # Do not specify DB password here otherwise application-{env} value is not used
    host: localhost
    port: 3306
    schema: diamonds
    jdbc-url: jdbc:mysql://${diamonds.datasource.host}:${diamonds.datasource.port}/${diamonds.datasource.schema}?autoReconnect=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-active: 10
    max-idle:  2
    max-wait: 10000
    min-evictable-idle-time-millis: 30000
    min-idle: 1
    test-while-idle: true
    time-between-eviction-runs-millis:  1
    test-on-borrow: true
    validation-query: SELECT 1

aws:
  region: us-east-1
  credentials:
    access:
      key: 
    secret:
      key: 
  server:
      timezone: America/New_York
